export const OPEN_SIDEBAR = 'OPEN_SIDEBAR'
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR'
export const SCROLL_ABOVE_HEADER = 'SCROLL_ABOVE_HEADER';
export const SCROLL_UNDER_HEADER = 'SCROLL_UNDER_HEADER';